/*  my1timer.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR("Xilinx Inc.");
MODULE_DESCRIPTION("my1timer - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "my1timer"

/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
uint val0 = 0x000000D0;
uint val1 = 0xFFF0DBDF;


module_param(val0, uint, S_IRUGO);
module_param(val1, uint, S_IRUGO);

struct my1timer_local *lp = NULL;


struct my1timer_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
};

static int  countInterrupt;


extern void setValueToAllLed(unsigned char v0,unsigned char v1,unsigned char v2,unsigned char v3);

static void OnOffLeds(unsigned char value)
{
	if(value)
	{
		setValueToAllLed(0x0F,50,50,50);
	}
	 
	 else
	 {
		setValueToAllLed(0x00,50,50,50);
	 }
	 
}

static irqreturn_t my1timer_irq(int irq, void *lp)
{
	//printk("my1timer interrupt !! counter=%d\n",countInterrupt++);
	unsigned int * p;
	p=((struct my1timer_local *)lp)->base_addr;
	p[0]=0x000001D0;/// reset axi timer interrupt bit
	OnOffLeds(countInterrupt%2);
	countInterrupt++;
	return IRQ_HANDLED;
}

static int my1timer_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct my1timer_local *lp = NULL;

	int rc = 0;
	dev_info(dev, "Device Tree Probing2\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct my1timer_local *) kmalloc(sizeof(struct my1timer_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate my1timer device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;

	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "my1timer: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

	
	volatile unsigned int * p;
	p=lp->base_addr;
	printk("Init AXI Timer\n");
    p[0]=0x00000050;
    p[1]=0xFFF0BDBF;
    p[0]|= 0x20;
    p[0]&=(~0x20);
    p[0]|=(1<<7);


	/* Get IRQ for the device */
	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
	if (!r_irq) {
		dev_info(dev, "no IRQ found\n");
		dev_info(dev, "my1timer at 0x%08x mapped to 0x%08x\n",
			(unsigned int __force)lp->mem_start,
			(unsigned int __force)lp->base_addr);
		return 0;
	}
	lp->irq = r_irq->start;
	rc = request_irq(lp->irq, &my1timer_irq, 0, DRIVER_NAME, lp);
	if (rc) {
		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
			lp->irq);
		goto error3;
	}

	dev_info(dev,"my1timer at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	return 0;
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int my1timer_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct my1timer_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}
#define CONFIG_OF
#ifdef CONFIG_OF
static struct of_device_id my1timer_of_match[] = {
	{ .compatible = "sam_solutions,my1timer", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, my1timer_of_match);
#else
# define my1timer_of_match
#endif


static struct platform_driver my1timer_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= my1timer_of_match,
	},
	.probe		= my1timer_probe,
	.remove		= my1timer_remove,
};

static int __init my1timer_init(void)
{
	printk("load for interrupt module\n");
	

	return platform_driver_register(&my1timer_driver);
}


static void __exit my1timer_exit(void)
{
	platform_driver_unregister(&my1timer_driver);
	printk(KERN_ALERT "Goodbye module world.\n");
}

module_init(my1timer_init);
module_exit(my1timer_exit);
